//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoDeTiempo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicio()
        {
            this.facturas = new HashSet<Factura>();
            this.movimientos = new HashSet<Movimiento>();
            this.solicitudes = new HashSet<Solicitud>();
        }
    
        public string id_servicio { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public string id_usuario { get; set; }
        public string id_categoria { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string tipo_servicio { get; set; }
    
        public virtual Categoria categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento> movimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud> solicitudes { get; set; }
        public virtual TipoServicio tipo_servicio1 { get; set; }
        public virtual Usuario usuarios { get; set; }
    }
}
