//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoDeTiempo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public string id_solicitud { get; set; }
        public string id_emisor { get; set; }
        public string concepto { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<bool> aceptada { get; set; }
    
        public virtual Servicio servicios { get; set; }
        public virtual Usuario usuarios { get; set; }
    }
}
